### ISSUE TITLE
How can i read data async from buffer

### ISSUE THREAD

**Issue by orcunor** [treehopper-electronics/HIDSharp#2]
I am trying make a basic win form application read data async from buffer when application start and tryna see whats bytes return from buffer show on listbox how can i write a function for this can anybody help me 
Im used ReadAsync function for this with await and async keyword but i can not call in form.cs

**Comment by jaydcarlson** [comment]
Hey @orcunor, this repo is a [fork from this website](https://www.zer7.com/software/hidsharp). We didn't write it, and we definitely can't support it. In general, issue trackers are a poor substitute for places like StackOverflow when it comes to general programming advice, so I'd recommend posting there. Be sure to include relevant snippets of your code (even if it doesn't compile or work), since it can help people figure out how you're approaching a problem. [This blog post](https://stephenhaunts.com/2014/10/14/using-async-and-await-to-update-the-ui-thread/comment-page-1/) might help with your specific issue. Good luck!
